using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Text;
using System.Text.Json.Serialization;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;

// ---------------------------------------------------------------------------
// Example API — the "minimalist extreme" implementation.
//
// The ENTIRE application lives in this one file: raw Minimal-API MapXxx calls
// with inline EF Core queries, inline validation and inline problem+json.
// No services, handlers, repositories, interfaces or validation libraries.
// It is still fully conformant with contract/openapi.yaml and conformance/.
// ---------------------------------------------------------------------------

var builder = WebApplication.CreateBuilder(args);

// --- Config (env overrides via Jwt__SecretKey, ConnectionStrings__Default, ...) ---
var cfg = builder.Configuration;
var jwtIssuer = cfg["Jwt:Issuer"] ?? "ExampleApi";
var jwtAudience = cfg["Jwt:Audience"] ?? "ExampleApiClient";
var jwtSecret = cfg["Jwt:SecretKey"] ?? "CHANGE-THIS-IN-PRODUCTION-use-a-long-random-secret-key";
var jwtMinutes = int.TryParse(cfg["Jwt:ExpirationMinutes"], out var mins) ? mins : 60;
if (jwtSecret.Length < 32)
    throw new InvalidOperationException("Jwt:SecretKey must be at least 32 characters for HS256.");
var connString = cfg.GetConnectionString("Default")
    ?? "Host=localhost;Port=5432;Database=exampleapi;Username=postgres;Password=postgres";
var signingKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(jwtSecret));

// --- Services ---
builder.Services.AddDbContext<AppDb>(o => o.UseNpgsql(connString));
builder.Services.AddProblemDetails();
builder.Services
    .AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddJwtBearer(o => o.TokenValidationParameters = new TokenValidationParameters
    {
        ValidateIssuer = true,
        ValidateAudience = true,
        ValidateLifetime = true,
        ValidateIssuerSigningKey = true,
        ValidIssuer = jwtIssuer,
        ValidAudience = jwtAudience,
        IssuerSigningKey = signingKey,
    });
builder.Services.AddAuthorization();

var app = builder.Build();

// --- Schema at startup: retry-connect until Postgres is ready, then CREATE TABLE.
//     xmin is a built-in PostgreSQL system column, so we never create it ourselves;
//     EF only reads it as the optimistic-concurrency token.
const string createSql = """
    CREATE TABLE IF NOT EXISTS articles (
        article_id  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name        varchar(64)   NOT NULL,
        description varchar(2048)  NOT NULL,
        category    varchar(64)    NULL,
        price       numeric(18,2)  NOT NULL,
        currency    varchar(3)     NULL
    );
    """;
using (var scope = app.Services.CreateScope())
{
    var db = scope.ServiceProvider.GetRequiredService<AppDb>();
    for (var attempt = 1; ; attempt++)
    {
        try { await db.Database.ExecuteSqlRawAsync(createSql); break; }
        catch when (attempt < 15) { await Task.Delay(TimeSpan.FromSeconds(2)); }
    }
}

app.UseAuthentication();
app.UseAuthorization();

// --- Supported ISO-4217 currency codes (49). ---
var currencies = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
{
    "USD","EUR","JPY","GBP","CHF","CAD","AUD","NZD","SEK","NOK","DKK","CZK","PLN","HUF","RON","BGN",
    "ISK","CNY","HKD","SGD","KRW","INR","THB","MYR","IDR","PHP","TWD","VND","BRL","MXN","ARS","CLP",
    "COP","PEN","AED","SAR","ILS","QAR","KWD","BHD","ZAR","TRY","RUB","UAH","EGP","NGN","KES","MAD","PKR",
};

// --- Inline helpers (local functions — the whole "domain layer"). ---
static ArticleRead ToRead(Article a) => new()
{
    ArticleId = a.ArticleId,
    Name = a.Name,
    Description = a.Description,
    Category = a.Category,
    Price = a.Price,
    Currency = a.Currency,
    RowVersion = a.RowVersion,
};

static IResult NotFound(int id) => Results.Problem(
    statusCode: 404, title: "Not Found",
    detail: $"Article with ID {id} was not found.",
    type: "https://httpstatuses.com/404");

// Returns null when valid, otherwise a field -> messages map (RFC 7807 "errors").
Dictionary<string, string[]>? Validate(ArticleWrite a, bool isUpdate)
{
    var errors = new Dictionary<string, List<string>>();
    void Add(string key, string msg)
    {
        if (!errors.TryGetValue(key, out var list)) errors[key] = list = new();
        list.Add(msg);
    }

    if (string.IsNullOrEmpty(a.Name)) Add("name", "Name is required.");
    else if (a.Name.Length > 64) Add("name", "Name must not exceed 64 characters.");

    if (string.IsNullOrEmpty(a.Description)) Add("description", "Description is required.");
    else if (a.Description.Length > 2048) Add("description", "Description must not exceed 2048 characters.");

    if (!string.IsNullOrEmpty(a.Category) && a.Category.Length > 64)
        Add("category", "Category must not exceed 64 characters.");

    if (a.Price < 0) Add("price", "Price must be greater than or equal to 0.");
    else if (a.Price > 9_999_999_999_999_999.99m) Add("price", "Price must not exceed 9,999,999,999,999,999.99.");

    if (a.Price > 0)
    {
        if (string.IsNullOrEmpty(a.Currency))
            Add("currency", "Currency is required when price is greater than 0.");
        else if (a.Currency.Length != 3 || !currencies.Contains(a.Currency))
            Add("currency", "Currency must be a supported ISO 4217 code.");
    }

    if (isUpdate && !(a.RowVersion.HasValue && a.RowVersion.Value >= 1))
        Add("row_version", "Row version is required and must be a non-zero value.");

    return errors.Count == 0 ? null : errors.ToDictionary(kv => kv.Key, kv => kv.Value.ToArray());
}

// ---------------------------------------------------------------------------
// Endpoints
// ---------------------------------------------------------------------------

app.MapGet("/health", () => Results.Ok(new { status = "healthy" }));

app.MapPost("/auth/token", (TokenRequest req) =>
{
    if (req.Username != "admin" || req.Password != "admin")
        return Results.Unauthorized();

    var expiresAt = DateTime.UtcNow.AddMinutes(jwtMinutes);
    var jwt = new JwtSecurityToken(
        issuer: jwtIssuer,
        audience: jwtAudience,
        claims: [new Claim(ClaimTypes.Name, req.Username)],
        expires: expiresAt,
        signingCredentials: new SigningCredentials(signingKey, SecurityAlgorithms.HmacSha256));

    var token = new JwtSecurityTokenHandler().WriteToken(jwt);
    return Results.Ok(new TokenResponse(token, expiresAt));
});

// GET /api/articles — filter (name partial/ci, category exact) + clamped pagination.
app.MapGet("/api/articles", async (
    AppDb db, string? name, string? category, int? page, int? pageSize) =>
{
    var query = db.Articles.AsNoTracking().AsQueryable();

    if (!string.IsNullOrWhiteSpace(name))
    {
        var esc = name.Replace("\\", "\\\\").Replace("%", "\\%").Replace("_", "\\_");
        query = query.Where(a => EF.Functions.ILike(a.Name, $"%{esc}%"));
    }
    if (!string.IsNullOrWhiteSpace(category))
        query = query.Where(a => a.Category == category);

    var totalCount = await query.CountAsync();
    var p = Math.Max(1, page ?? 1);
    var ps = Math.Clamp(pageSize ?? 10, 1, 100);           // clamp, never reject
    var items = await query
        .OrderBy(a => a.ArticleId)
        .Skip((p - 1) * ps).Take(ps)
        .ToListAsync();
    var totalPages = (int)Math.Ceiling(totalCount / (double)ps);

    return Results.Ok(new
    {
        items = items.Select(ToRead).ToList(),
        page = p,
        pageSize = ps,
        totalCount,
        totalPages,
        hasPrevious = p > 1,
        hasNext = p < totalPages,
    });
}).RequireAuthorization();

// POST /api/articles — create.
app.MapPost("/api/articles", async (AppDb db, ArticleWrite body) =>
{
    var errors = Validate(body, isUpdate: false);
    if (errors is not null) return Results.ValidationProblem(errors);

    var a = new Article
    {
        Name = body.Name,
        Description = body.Description,
        Category = body.Category,
        Price = body.Price,
        Currency = body.Currency,
    };
    db.Articles.Add(a);
    await db.SaveChangesAsync();

    return Results.Created($"/api/articles/{a.ArticleId}", ToRead(a));
}).RequireAuthorization();

// GET /api/articles/{id}
app.MapGet("/api/articles/{id:int}", async (AppDb db, int id) =>
{
    var a = await db.Articles.AsNoTracking().FirstOrDefaultAsync(x => x.ArticleId == id);
    return a is null ? NotFound(id) : Results.Ok(ToRead(a));
}).RequireAuthorization();

// PUT /api/articles/{id} — full update with optimistic concurrency on xmin.
app.MapPut("/api/articles/{id:int}", async (AppDb db, int id, ArticleWrite body) =>
{
    var errors = Validate(body, isUpdate: true);
    if (errors is not null) return Results.ValidationProblem(errors);

    var a = await db.Articles.FindAsync(id);
    if (a is null) return NotFound(id);

    // EF compares this original xmin against the current DB value on save.
    db.Entry(a).Property(x => x.RowVersion).OriginalValue = body.RowVersion!.Value;
    a.Name = body.Name;
    a.Description = body.Description;
    a.Category = body.Category;
    a.Price = body.Price;
    a.Currency = body.Currency;

    try
    {
        await db.SaveChangesAsync();
    }
    catch (DbUpdateConcurrencyException)
    {
        return Results.Problem(
            statusCode: 409, title: "Conflict",
            detail: $"Article with ID {id} was modified by another request. Please retry.",
            type: "https://httpstatuses.com/409");
    }

    return Results.Ok(ToRead(a));
}).RequireAuthorization();

// DELETE /api/articles/{id}
app.MapDelete("/api/articles/{id:int}", async (AppDb db, int id) =>
{
    var a = await db.Articles.FindAsync(id);
    if (a is null) return NotFound(id);

    db.Articles.Remove(a);
    await db.SaveChangesAsync();
    return Results.NoContent();
}).RequireAuthorization();

// POST /api/articles-concurrent — batch create (array in, array out, same order).
app.MapPost("/api/articles-concurrent", async (AppDb db, List<ArticleWrite> body) =>
{
    if (body is null || body.Count == 0)
        return Results.ValidationProblem(new Dictionary<string, string[]>
        {
            ["items"] = ["At least one article is required."],
        });
    if (body.Count > 100)
        return Results.ValidationProblem(new Dictionary<string, string[]>
        {
            ["items"] = ["Cannot create more than 100 articles at once."],
        });

    for (var i = 0; i < body.Count; i++)
    {
        var errors = Validate(body[i], isUpdate: false);
        if (errors is not null)
            return Results.ValidationProblem(
                errors.ToDictionary(kv => $"[{i}].{kv.Key}", kv => kv.Value));
    }

    var entities = body.Select(w => new Article
    {
        Name = w.Name,
        Description = w.Description,
        Category = w.Category,
        Price = w.Price,
        Currency = w.Currency,
    }).ToList();

    db.Articles.AddRange(entities);
    await db.SaveChangesAsync();

    return Results.Created("/api/articles", entities.Select(ToRead).ToList());
}).RequireAuthorization();

app.Run();

// ---------------------------------------------------------------------------
// Types (must come after top-level statements)
// ---------------------------------------------------------------------------

/// <summary>EF entity backing the <c>articles</c> table.</summary>
public sealed class Article
{
    public int ArticleId { get; set; }
    public string Name { get; set; } = string.Empty;
    public string Description { get; set; } = string.Empty;
    public string? Category { get; set; }
    public decimal Price { get; set; }
    public string? Currency { get; set; }

    /// <summary>Maps to the PostgreSQL <c>xmin</c> system column (concurrency token).</summary>
    public uint RowVersion { get; set; }
}

/// <summary>Minimal EF Core context — one entity, snake_case columns, xmin as row version.</summary>
public sealed class AppDb(DbContextOptions<AppDb> options) : DbContext(options)
{
    public DbSet<Article> Articles => Set<Article>();

    protected override void OnModelCreating(ModelBuilder b)
    {
        b.Entity<Article>(e =>
        {
            e.ToTable("articles");
            e.HasKey(a => a.ArticleId);
            e.Property(a => a.ArticleId).HasColumnName("article_id").ValueGeneratedOnAdd();
            e.Property(a => a.Name).HasColumnName("name").IsRequired().HasMaxLength(64);
            e.Property(a => a.Description).HasColumnName("description").IsRequired().HasMaxLength(2048);
            e.Property(a => a.Category).HasColumnName("category").HasMaxLength(64);
            e.Property(a => a.Price).HasColumnName("price").HasColumnType("numeric(18,2)");
            e.Property(a => a.Currency).HasColumnName("currency").HasMaxLength(3);

            // xmin: PostgreSQL system column, auto-incremented on every row change.
            e.Property(a => a.RowVersion)
                .HasColumnName("xmin").HasColumnType("xid")
                .ValueGeneratedOnAddOrUpdate()
                .IsRowVersion()
                .IsConcurrencyToken();
        });
    }
}

/// <summary>Create / update / batch request body (snake_case wire fields).</summary>
public sealed class ArticleWrite
{
    [JsonPropertyName("name")] public string Name { get; set; } = string.Empty;
    [JsonPropertyName("description")] public string Description { get; set; } = string.Empty;
    [JsonPropertyName("category")] public string? Category { get; set; }
    [JsonPropertyName("price")] public decimal Price { get; set; }
    [JsonPropertyName("currency")] public string? Currency { get; set; }

    /// <summary>Required on update only; ignored for create/batch.</summary>
    [JsonPropertyName("row_version")] public uint? RowVersion { get; set; }
}

/// <summary>Article response body (snake_case wire fields).</summary>
public sealed class ArticleRead
{
    [JsonPropertyName("article_id")] public int ArticleId { get; set; }
    [JsonPropertyName("name")] public string Name { get; set; } = string.Empty;
    [JsonPropertyName("description")] public string Description { get; set; } = string.Empty;
    [JsonPropertyName("category")] public string? Category { get; set; }
    [JsonPropertyName("price")] public decimal Price { get; set; }
    [JsonPropertyName("currency")] public string? Currency { get; set; }
    [JsonPropertyName("row_version")] public uint RowVersion { get; set; }
}

/// <summary>Token request (camelCase wire fields).</summary>
public sealed record TokenRequest(string Username, string Password);

/// <summary>Token response (camelCase wire fields).</summary>
public sealed record TokenResponse(
    [property: JsonPropertyName("token")] string Token,
    [property: JsonPropertyName("expiresAt")] DateTime ExpiresAt);
